import type { KirletTableDecl } from "@opus-perpetuus/imperium-core-kit";

export const physical_device_tables: KirletTableDecl[] = [
  {
    name: "physical_device",
    columns: [
      { name: "id", type: "text", primaryKey: true },
      { name: "name", type: "text", notNull: true },
      { name: "description", type: "text" },
      { name: "is_active", type: "boolean", notNull: true, default: true },
      { name: "state", type: "text" },
      { name: "ref", type: "text", unique: true },
      { name: "search_field", type: "text" },
      { name: "created_by", type: "text" },
      { name: "custom_data", type: "json" },
      { name: "payload", type: "json" },
      { name: "created_at", type: "text", notNull: true },
      { name: "updated_at", type: "text", notNull: true },
      { name: "hostname", type: "text" },
      { name: "model", type: "text" },
      { name: "serial", type: "text" },
      { name: "os_platform", type: "text" },
      { name: "last_user_name", type: "text" },
      { name: "last_seen", type: "text" },
      { name: "install_uuid", type: "text" },
      { name: "machine_uuid", type: "text" },
      { name: "manufacturer", type: "text" },
      { name: "os_distro", type: "text" },
      { name: "os_release", type: "text" },
      { name: "os_arch", type: "text" },
      { name: "cpu_brand", type: "text" },
      { name: "cpu_cores", type: "real" },
      { name: "memory_total_bytes", type: "real" },
      { name: "gpu_primary", type: "text" },
      { name: "primary_mac", type: "text" },
      { name: "primary_ip4", type: "text" },
      { name: "device_kind", type: "text" },
      { name: "app_version", type: "text" },
      { name: "last_user_id", type: "text" },
    ],
    indexes: [
      { name: "idx_physical_device_name", columns: ["name"] },
      { name: "idx_physical_device_active", columns: ["is_active"] },
    ],
  },
];
